sudo: required
dist: trusty

virtualenv:
    system_site_packages: true
python:
    - "2.7"
before_install:
    - sudo apt-get -y install python-software-properties
    - sudo add-apt-repository -y ppa:saltstack/salt
    - sudo apt-get update
    - wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
    - sudo ssh-keygen -f /root/.ssh/id_rsa  -N ''
    - sudo su -c 'cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys'
    - ssh-keyscan $(hostname -f)| sudo tee -a /root/.ssh/known_hosts
install:
    - sudo apt-get -y install salt-minion salt-common python-jinja2
    - sudo salt-call --retcode-passthrough --local state.template vagrant/devmode/salt/roots/build_deps.sls
    - sudo salt-call --retcode-passthrough --local state.template vagrant/devmode/salt/roots/install_ceph.sls
    - virtualenv --system-site-packages env
    - source env/bin/activate
    - sudo chown travis:travis -R /home/travis/.cache
    - pip install -r requirements/lite.txt
    - pip install flake8
    - pip install django-nose
    - pip install mock
    - for m in rest-api minion-sim cthulhu calamari-web calamari-common calamari-lite; do cd $m ; python setup.py develop ; cd .. ; done
    - cd dev ; python ./configure.py ; cd ..
    - CALAMARI_CONFIG=dev/calamari.conf calamari-ctl initialize --admin-username admin --admin-password admin --admin-email admin@admin.com
    - CALAMARI_CONFIG=dev/calamari.conf calamari-ctl initialize
    - ls -al /etc/ceph

script:
    - "make lint"
    - "make unit-tests"
